from __future__ import annotations

import argparse
import json
from collections.abc import Iterable
from pathlib import Path
from typing import Any, cast

from app.apis.contract import ApiContract
from app.apis.contracts import OPERATIONS
from app.main import app
from tools.api_analysis import analyze_operation, integration_implementation, participant

ROOT = Path(__file__).resolve().parents[3]
DOCS_ROOT = ROOT / "docs/spec/40.apis"
JsonObject = dict[str, Any]

COMMENTS = {
    "api-list": "<!-- This file is generated by uv run python -m "
    "tools.generate_api_list. Do not edit manually. -->",
    "if": "<!-- This file is generated by uv run python -m "
    "tools.generate_openapi_if_specs. Do not edit manually. -->",
    "detail": "<!-- This file is generated by uv run python -m "
    "tools.generate_api_detail_design. Do not edit manually. -->",
    "sequence": "<!-- This file is generated by uv run python -m "
    "tools.generate_api_sequences. Do not edit manually. -->",
    "unit-test": "<!-- This file is generated by uv run python -m "
    "tools.generate_api_unit_test_factors. Do not edit manually. -->",
    "messages": "<!-- generated by tools/python/tools/"
    "generate_api_message_catalog.py; do not edit. -->",
    "query": "<!-- This file is generated by uv run python -m "
    "tools.generate_query_specs. Do not edit manually. -->",
}


def _openapi() -> JsonObject:
    return app.openapi()


def _operation(schema: JsonObject, contract: ApiContract) -> JsonObject:
    paths = cast(JsonObject, schema["paths"])
    path_item = cast(JsonObject, paths[contract.path])
    return cast(JsonObject, path_item[contract.method.lower()])


def _schema_name(value: object) -> str | None:
    if not isinstance(value, dict):
        return None
    reference = cast(JsonObject, value).get("$ref")
    return str(reference).rsplit("/", maxsplit=1)[-1] if isinstance(reference, str) else None


def _request_schema(schema: JsonObject, operation: JsonObject) -> tuple[str | None, JsonObject]:
    request_body = operation.get("requestBody")
    if not isinstance(request_body, dict):
        return None, {}
    content = cast(JsonObject, request_body).get("content")
    if not isinstance(content, dict):
        return None, {}
    media = cast(JsonObject, content).get("application/json")
    if not isinstance(media, dict):
        return None, {}
    schema_ref = cast(JsonObject, media).get("schema")
    name = _schema_name(schema_ref)
    return name, _component_schema(schema, name)


def _response_schema(schema: JsonObject, operation: JsonObject) -> tuple[str | None, JsonObject]:
    responses = operation.get("responses")
    if not isinstance(responses, dict):
        return None, {}
    response_map = cast(JsonObject, responses)
    success_key = next((key for key in ("200", "201", "202", "204") if key in response_map), None)
    if success_key is None or not isinstance(response_map[success_key], dict):
        return None, {}
    content = cast(JsonObject, response_map[success_key]).get("content")
    if not isinstance(content, dict):
        return None, {}
    media = cast(JsonObject, content).get("application/json")
    if not isinstance(media, dict):
        return None, {}
    schema_ref = cast(JsonObject, media).get("schema")
    name = _schema_name(schema_ref)
    return name, _component_schema(schema, name)


def _component_schema(schema: JsonObject, name: str | None) -> JsonObject:
    if name is None:
        return {}
    components = schema.get("components")
    if not isinstance(components, dict):
        return {}
    schemas = cast(JsonObject, components).get("schemas")
    if not isinstance(schemas, dict):
        return {}
    value = cast(JsonObject, schemas).get(name)
    return cast(JsonObject, value) if isinstance(value, dict) else {}


def _type_name(field: JsonObject) -> str:
    if "$ref" in field:
        return str(field["$ref"]).rsplit("/", maxsplit=1)[-1]
    if "anyOf" in field:
        return " | ".join(
            _type_name(cast(JsonObject, item))
            for item in cast(list[object], field["anyOf"])
            if isinstance(item, dict)
        )
    field_type = str(field.get("type", "object"))
    if field_type == "array" and isinstance(field.get("items"), dict):
        return f"list[{_type_name(cast(JsonObject, field['items']))}]"
    return field_type


def _fields(model: JsonObject) -> list[tuple[str, str, str]]:
    properties = model.get("properties")
    if not isinstance(properties, dict):
        return []
    rows: list[tuple[str, str, str]] = []
    for name, raw in cast(JsonObject, properties).items():
        field = cast(JsonObject, raw) if isinstance(raw, dict) else {}
        rows.append((name, _type_name(field), str(field.get("description", "-"))))
    return rows


def _parameters(operation: JsonObject, location: str) -> list[JsonObject]:
    raw = operation.get("parameters")
    if not isinstance(raw, list):
        return []
    parameters: list[JsonObject] = []
    for item in cast(list[object], raw):
        if not isinstance(item, dict):
            continue
        parameter = cast(JsonObject, item)
        if parameter.get("in") == location:
            parameters.append(parameter)
    return parameters


def render_api_list(schema: JsonObject) -> str:
    lines = [
        COMMENTS["api-list"],
        "",
        "# API list",
        "",
        "| Tag | Method | Path | Summary |",
        "| --- | --- | --- | --- |",
    ]
    for contract in OPERATIONS:
        operation = _operation(schema, contract)
        tags = operation.get("tags")
        tag_values = cast(list[object], tags) if isinstance(tags, list) else []
        tag = str(tag_values[0]) if tag_values else "-"
        lines.append(f"| `{tag}` | `{contract.method}` | `{contract.path}` | {contract.summary} |")
    return "\n".join(lines) + "\n"


def _parameter_section(title: str, parameters: list[JsonObject]) -> list[str]:
    lines = [f"## {title}", ""]
    if not parameters:
        return [*lines, "_None._", ""]
    lines.extend(["| Name | Type | Required | Description |", "| --- | --- | --- | --- |"])
    for parameter in parameters:
        schema = cast(JsonObject, parameter.get("schema", {}))
        required = str(bool(parameter.get("required"))).lower()
        description = parameter.get("description", "-")
        lines.append(
            f"| `{parameter.get('name', '-')}` | `{_type_name(schema)}` | "
            f"`{required}` | {description} |"
        )
    return [*lines, ""]


def render_if(schema: JsonObject, contract: ApiContract) -> str:
    operation = _operation(schema, contract)
    request_name, request_model = _request_schema(schema, operation)
    responses = cast(JsonObject, operation.get("responses", {}))
    lines = [COMMENTS["if"], "", f"# {contract.method} {contract.path}", ""]
    headers = (
        []
        if contract.auth_mode == "public"
        else [
            {
                "name": "Authorization",
                "schema": {"type": "string"},
                "required": True,
                "description": "Cognito access tokenをBearer形式で指定します。",
            }
        ]
    )
    lines.extend(_parameter_section("Headers", headers))
    lines.extend(_parameter_section("Path Parameters", _parameters(operation, "path")))
    lines.extend(_parameter_section("Query Parameters", _parameters(operation, "query")))
    lines.extend(["## Data", ""])
    if request_name is None:
        lines.extend(["_Request body はありません。_", ""])
    else:
        lines.extend(
            [
                f"Schema: `{request_name}`",
                "",
                "| Name | Type | Description |",
                "| --- | --- | --- |",
            ]
        )
        lines.extend(
            f"| `{name}` | `{type_name}` | {description} |"
            for name, type_name, description in _fields(request_model)
        )
        lines.append("")
    lines.extend(["## Responses", "", "| Status | Description |", "| --- | --- |"])
    for code, raw in sorted(responses.items()):
        response = cast(JsonObject, raw) if isinstance(raw, dict) else {}
        lines.append(f"| `{code}` | {response.get('description', '-')} |")
    lines.extend(["", "## Samples", ""])
    for code, raw in sorted(responses.items()):
        response = cast(JsonObject, raw) if isinstance(raw, dict) else {}
        content = response.get("content")
        media = (
            cast(JsonObject, content).get("application/json") if isinstance(content, dict) else None
        )
        example = cast(JsonObject, media).get("example") if isinstance(media, dict) else None
        lines.extend([f"### HTTP {code}", ""])
        lines.extend(
            [
                "```json",
                json.dumps(
                    example or {"status": int(code) if str(code).isdigit() else code},
                    ensure_ascii=False,
                    indent=2,
                ),
                "```",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def render_detail(schema: JsonObject, contract: ApiContract) -> str:
    analysis = analyze_operation(contract)
    operation = _operation(schema, contract)
    request_name, request_model = _request_schema(schema, operation)
    response_name, response_model = _response_schema(schema, operation)
    endpoint_inputs = [
        *_parameters(operation, "path"),
        *_parameters(operation, "query"),
        *_parameters(operation, "header"),
    ]
    lines = [
        COMMENTS["detail"],
        "",
        f"# {contract.api} detail design",
        "",
        f"- Operation: `{contract.operation_id}`",
        f"- Endpoint: `{contract.method} {contract.path}`",
        "",
        "## 1. 正常系入力",
        "",
        "| Location | Name | Type | 説明 |",
        "| --- | --- | --- | --- |",
    ]
    for parameter in endpoint_inputs:
        parameter_schema = cast(JsonObject, parameter.get("schema", {}))
        location = parameter.get("in", "-")
        name = parameter.get("name", "-")
        description = parameter.get("description", "-")
        lines.append(
            f"| `{location}` | `{name}` | `{_type_name(parameter_schema)}` | {description} |"
        )
    if request_name is None:
        lines.extend(["", "_Request body はありません。_"])
    else:
        lines.extend(
            [
                "",
                f"### Request body `{request_name}`",
                "",
                "| 項目 | 型 | 説明 |",
                "| --- | --- | --- |",
            ]
        )
        lines.extend(
            f"| `{name}` | `{type_name}` | {description} |"
            for name, type_name, description in _fields(request_model)
        )
    lines.extend(["", "## 2. 正常系前提", ""])
    prerequisites = (
        [] if contract.auth_mode == "public" else ["Bearer access tokenが検証済みである。"]
    )
    prerequisites.extend(
        f"条件分岐: {condition}: 不成立"
        for step in analysis.steps
        for condition in step.function.conditions
    )
    lines.extend(
        [f"- {item}" for item in prerequisites]
        or ["- 条件分岐または例外処理の正常系前提はありません。"]
    )
    lines.extend(["", "## 3. 正常系リソース変更", ""])
    changes = [
        (step.function.description, call)
        for step in analysis.steps
        for call in step.function.integrations
        if call.method in {"replace_document", "emit"}
        and not (call.event or "").endswith("permission_denied")
    ]
    if not changes:
        lines.append("_正常系で作成/更新/削除するリソースはありません。_")
    for description, call in changes:
        lines.extend(
            [
                f"### 外部リソース `{call.resource}.{call.method}`",
                "",
                f"- 目的: {description}",
                f"- 実装: {integration_implementation(call.resource)}",
                "",
            ]
        )
    lines.extend(["", "## 4. 正常系レスポンス", ""])
    if response_name is None:
        lines.append("_Response model はありません。_")
    else:
        sources = dict(contract.response_sources)
        lines.extend(
            [
                f"- Response model: `{response_name}`",
                "",
                "| 項目 | 説明 | 値の取得元 |",
                "| --- | --- | --- |",
            ]
        )
        lines.extend(
            f"| `{name}` | {description} | {sources.get(name, 'Operation function')} |"
            for name, _type_name_value, description in _fields(response_model)
        )
    return "\n".join(lines).rstrip() + "\n"


def _port_name(resource: str) -> str:
    return {
        "chunk_store": "ChunkStorePort",
        "embedder": "EmbedderPort",
        "answer_generator": "AnswerGeneratorPort",
        "audit_log": "audit",
    }.get(resource, resource)


def _error_response(error: str) -> str:
    if error.startswith("PermissionError"):
        return "HTTP 403 Forbidden"
    if error.startswith("ValueError"):
        return "HTTP 400 Bad Request"
    return "HTTP 500 Internal Server Error"


def render_sequence(contract: ApiContract) -> str:
    analysis = analyze_operation(contract)
    lines = [
        COMMENTS["sequence"],
        "",
        f"# {contract.api} sequence",
        "",
        "```mermaid",
        "sequenceDiagram",
        "  autonumber",
        "  participant User as User",
        "  participant API as API",
    ]
    resources = tuple(dict.fromkeys(call.resource for call in analysis.integrations))
    for resource in resources:
        identifier, label = participant(resource)
        lines.append(f"  participant {identifier} as {label}")
    lines.append(f"  User->>API: {contract.method} {contract.path}")
    if contract.auth_mode != "public":
        lines.extend(
            [
                "  alt Bearer access tokenが未指定または検証できない場合。",
                "    API-->>User: HTTP 401 Unauthorized<br/>Bearer authentication is required",
                "  end",
                "  alt Request bodyが型または制約に一致しない場合。",
                "    API-->>User: HTTP 422 Unprocessable Content<br/>request validation failed",
                "  end",
            ]
        )
    for step in analysis.steps:
        indent = "  "
        if step.condition:
            lines.append(f"  alt {step.condition}")
            indent = "    "
        conditional_audits = [
            call
            for call in step.function.integrations
            if (call.event or "").endswith("permission_denied")
        ]
        for index, condition in enumerate(step.function.conditions):
            lines.append(f"{indent}alt {condition}")
            for call in conditional_audits:
                identifier, _label = participant(call.resource)
                lines.append(f"{indent}  API->>{identifier}: {call.event}<br/>Port audit.emit")
            error = (
                step.function.raised_errors[index]
                if index < len(step.function.raised_errors)
                else "operation error"
            )
            lines.append(f"{indent}  API-->>User: {_error_response(error)}<br/>{error}")
            lines.append(f"{indent}end")
        regular_calls = [
            call
            for call in step.function.integrations
            if not (call.event or "").endswith("permission_denied")
        ]
        if not regular_calls:
            lines.append(f"{indent}API->>API: {step.function.description}")
        for call in regular_calls:
            identifier, _label = participant(call.resource)
            operation = call.event or f"{_port_name(call.resource)}.{call.method}"
            lines.append(
                f"{indent}API->>{identifier}: {step.function.description}"
                f"<br/>Port {operation}"
                f"<br/>実装 {integration_implementation(call.resource)}"
            )
        if step.condition:
            lines.append("  end")
    lines.extend(["  API-->>User: HTTP success response", "```", ""])
    return "\n".join(lines)


def render_unit_test(contract: ApiContract) -> str:
    factors = analyze_operation(contract).factors
    lines = [
        COMMENTS["unit-test"],
        "",
        f"# {contract.api} unit test factors",
        "",
        f"- Operation: `{contract.operation_id}`",
        f"- Endpoint: `{contract.method} {contract.path}`",
        "",
        "## 0. Router層の暗黙処理",
        "",
        "| 要因 | 要素 | 期待観点 |",
        "| --- | --- | --- |",
        "| 認証/入力検証 | 正常 | operation処理へ進む。 |",
        "| 認証/入力検証 | 異常 | OpenAPI定義どおりのerror responseを返す。 |",
        "",
        "## 1. 要因ごとの要素",
        "",
    ]
    for index, factor in enumerate(factors, start=1):
        lines.extend(
            [
                f"### F{index:02d} {factor}",
                "",
                "| 要素 | 期待観点 |",
                "| --- | --- |",
                "| 成立 | 対象処理または条件成立側を実行する。 |",
                "| 不成立/例外 | 定義済みerror responseを返し、後続の副作用を行わない。 |",
                "",
            ]
        )
    lines.extend(
        [
            "## 2. 直積したテストケース一覧",
            "",
            "| Test case | 主要素 | 期待結果 |",
            "| --- | --- | --- |",
            "| `TC001` | 全要因正常 | API正常応答 |",
        ]
    )
    for index, factor in enumerate(factors, start=2):
        lines.append(f"| `TC{index:03d}` | {factor}: 異常 | 契約済みerror response |")
    lines.extend(["", "## 3. テスト詳細", ""])
    for index, factor in enumerate(("正常系", *factors), start=1):
        expected = "HTTP success response" if index == 1 else "副作用を中断しerror responseを返す。"
        lines.extend(
            [
                f"### TC{index:03d}",
                "",
                "| 要因 | 要素 | 期待観点 |",
                "| --- | --- | --- |",
                f"| 対象 | {factor} | {expected} |",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def render_messages(contract: ApiContract) -> str:
    lines = [
        COMMENTS["messages"],
        "",
        f"# Message catalog: `{contract.markdown_slug}`",
        "",
        "## API",
        "",
        f"- Operation: `{contract.operation_id}`",
        f"- Endpoint: `{contract.method} {contract.path}`",
        "",
        "## 生成・検証方針",
        "",
        "- `message_catalog.py` とoperation contractを正本として生成する。",
        "- message ID、level、運用対応、出力項目をstrict検証する。",
        "",
        "## メッセージ一覧",
        "",
        "| ID | Message ID | Level | Summary |",
        "| --- | --- | --- | --- |",
    ]
    for message in contract.messages:
        lines.append(
            f"| `{message.catalog_id}` | `{message.message_id}` | "
            f"`{message.level}` | {message.summary} |"
        )
    lines.extend(["", "## ログ詳細", ""])
    for message in contract.messages:
        lines.extend(
            [
                f"### `{message.catalog_id}` `{message.message_id}`",
                "",
                f"- Level: `{message.level}`",
                f"- Summary: {message.summary}",
                f"- When: {message.when}",
                f"- Operator action: {message.operator_action}",
                f"- Runbook: `{message.runbook}`",
                f"- Output fields: {', '.join(f'`{field}`' for field in message.output_fields)}",
                "",
            ]
        )
    lines.extend(
        [
            "## strict検証で要求する項目",
            "",
            "- catalog IDとmessage IDがoperation内で一意であること。",
            "- level、発生条件、operator action、runbook、output fieldsが欠落しないこと。",
            "",
        ]
    )
    return "\n".join(lines)


def render_query(contract: ApiContract) -> str:
    analysis = analyze_operation(contract)
    queries = [
        (step.function, call)
        for step in analysis.steps
        for call in step.function.integrations
        if call.resource == "chunk_store"
    ]
    lines = [
        COMMENTS["query"],
        "",
        f"# {contract.api} query",
    ]
    if not queries:
        lines.extend(["", "_DB queryはありません。_", ""])
        return "\n".join(lines)
    for function, call in queries:
        query_type = "WRITE" if call.method == "replace_document" else "HYBRID READ"
        argument_rows = [
            f"| `{argument.split(':', maxsplit=1)[0]}` | "
            f"`{argument.split(':', maxsplit=1)[1].strip()}` |"
            for argument in function.arguments
        ]
        conditions = [f"- {condition}" for condition in function.conditions]
        lines.extend(
            [
                "",
                f"## ChunkStorePort.{call.method}",
                "",
                "### Query種別",
                "",
                f"`{query_type}`",
                "",
                "### Queryの概要",
                "",
                function.description,
                "",
                "### 利用するデータストア",
                "",
                "- Local: `InMemoryChunkStore`",
                "- AWS: `Bedrock Knowledge Base` + `S3 Vectors`",
                "",
                "### 引数",
                "",
                "| 項目 | 型 |",
                "| --- | --- |",
                *argument_rows,
                "",
                "### 戻り値",
                "",
                f"`{function.return_type}`",
                "",
                "### 条件",
                "",
                *(conditions or ["_追加条件はありません。_"]),
                "",
            ]
        )
    return "\n".join(lines)


def render_message_index() -> str:
    lines = [
        COMMENTS["messages"],
        "",
        "# API message catalog index",
        "",
        "| domain | api | route | id | message_id | level | status | ログ概要 | "
        "出力項目 | 対応すべきこと | runbook | output |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for contract in OPERATIONS:
        for message in contract.messages:
            output = f"docs/spec/40.apis/{contract.markdown_slug}/messages_gen.md"
            fields = ", ".join(message.output_fields)
            lines.append(
                "| "
                + " | ".join(
                    (
                        f"`{contract.domain}`",
                        f"`{contract.api}`",
                        f"`{contract.method} {contract.path}`",
                        f"`{message.catalog_id}`",
                        f"`{message.message_id}`",
                        f"`{message.level}`",
                        "`-`",
                        message.summary,
                        fields,
                        message.operator_action,
                        f"`{message.runbook}`",
                        f"`{output}`",
                    )
                )
                + " |"
            )
    return "\n".join(lines) + "\n"


def render_outputs(kinds: Iterable[str] | None = None) -> dict[Path, str]:
    selected = set(
        kinds or {"api-list", "if", "detail", "sequence", "unit-test", "messages", "query"}
    )
    schema = _openapi()
    outputs: dict[Path, str] = {}
    if "api-list" in selected:
        outputs[DOCS_ROOT / "apis_list_gen.md"] = render_api_list(schema)
    for contract in OPERATIONS:
        target = DOCS_ROOT / contract.markdown_slug
        if "if" in selected:
            outputs[target / "if_gen.md"] = render_if(schema, contract)
        if "detail" in selected:
            outputs[target / "detail-design_gen.md"] = render_detail(schema, contract)
        if "sequence" in selected:
            outputs[target / "sequence_gen.md"] = render_sequence(contract)
        if "unit-test" in selected:
            outputs[target / "unit-test_gen.md"] = render_unit_test(contract)
        if "messages" in selected:
            outputs[target / "messages_gen.md"] = render_messages(contract)
        if "query" in selected:
            outputs[target / "query_gen.md"] = render_query(contract)
    if "messages" in selected:
        outputs[DOCS_ROOT / "messages_index_gen.md"] = render_message_index()
    return outputs


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check_outputs(outputs: dict[Path, str]) -> int:
    stale = [
        str(path.relative_to(ROOT))
        for path, content in outputs.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if stale:
        raise SystemExit("stale generated docs: " + ", ".join(stale))
    return 0


def run(kinds: Iterable[str] | None, argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate Lazunex-compatible API design documents."
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    outputs = render_outputs(kinds)
    if args.check:
        return check_outputs(outputs)
    write_outputs(outputs)
    return 0
