import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs"
import path from "node:path"
import * as cdk from "aws-cdk-lib"
import { RagEngineeringStack } from "../lib/rag-engineering-stack"

const app=new cdk.App(); const stack=new RagEngineeringStack(app,"InventoryStack")
const artifact=app.synth().getStackArtifact(stack.artifactId)
const resources=(artifact.template.Resources ?? {}) as Record<string,{Type:string}>
const counts=new Map<string,number>()
for (const resource of Object.values(resources)) counts.set(resource.Type,(counts.get(resource.Type)??0)+1)
const body=["<!-- Generated by npm run docs:infra. Do not edit. -->","","# Infrastructure inventory","","| CloudFormation type | Count |","|---|---:|",...[...counts].sort().map(([type,count])=>`| \`${type}\` | ${count} |`),""].join("\n")
const output=path.resolve(__dirname,"../../docs/generated/infra-inventory.md")
if (process.argv.includes("--check")) { if(!existsSync(output)||readFileSync(output,"utf8")!==body) throw new Error("infra inventory is stale") }
else { mkdirSync(path.dirname(output),{recursive:true}); writeFileSync(output,body) }

