import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs"
import path from "node:path"
import * as cdk from "aws-cdk-lib"
import { RagEngineeringStack } from "../lib/rag-engineering-stack"

const app=new cdk.App(); const stack=new RagEngineeringStack(app,"InventoryStack")
const artifact=app.synth().getStackArtifact(stack.artifactId)
type TemplateResource={ Type:string; DeletionPolicy?:string; Properties?:unknown }
type TemplateParameter={ Type?:string; Default?:unknown; Description?:string }
type TemplateOutput={ Description?:string }
type CloudFormationTemplate={
  Resources?:Record<string,TemplateResource>
  Parameters?:Record<string,TemplateParameter>
  Outputs?:Record<string,TemplateOutput>
}
const template=artifact.template as CloudFormationTemplate
const resources=template.Resources ?? {}
const counts=new Map<string,number>()
for (const resource of Object.values(resources)) counts.set(resource.Type,(counts.get(resource.Type)??0)+1)
const actions=new Set<string>()
collectActions(resources,actions)
const body=[
  "<!-- Generated by npm run docs:infra. Do not edit. -->",
  "",
  "# Infrastructure design inventory",
  "",
  "## Resource summary",
  "",
  "| CloudFormation type | Count |",
  "|---|---:|",
  ...[...counts].sort().map(([type,count])=>`| \`${type}\` | ${count} |`),
  "",
  "## Resources and retention",
  "",
  "| Logical ID | Type | Deletion policy |",
  "|---|---|---|",
  ...Object.entries(resources).sort().map(([id,resource])=>`| \`${id}\` | \`${resource.Type}\` | \`${resource.DeletionPolicy ?? "Delete"}\` |`),
  "",
  "## Parameters",
  "",
  "| Name | Type | Default | Description |",
  "|---|---|---|---|",
  ...Object.entries(template.Parameters ?? {}).sort().map(([name,parameter])=>`| \`${name}\` | \`${parameter.Type ?? "-"}\` | ${parameter.Default === undefined ? "required" : `\`${String(parameter.Default)}\``} | ${parameter.Description ?? "-"} |`),
  "",
  "## Outputs",
  "",
  "| Name | Description |",
  "|---|---|",
  ...Object.entries(template.Outputs ?? {}).sort().map(([name,output])=>`| \`${name}\` | ${output.Description ?? "-"} |`),
  "",
  "## IAM action inventory",
  "",
  ...[...actions].sort().map(action=>`- \`${action}\``),
  ""
].join("\n")
const output=path.resolve(__dirname,"../../docs/generated/infra-inventory.md")
if (process.argv.includes("--check")) { if(!existsSync(output)||readFileSync(output,"utf8")!==body) throw new Error("infra inventory is stale") }
else { mkdirSync(path.dirname(output),{recursive:true}); writeFileSync(output,body) }

function collectActions(value:unknown,actions:Set<string>):void {
  if (Array.isArray(value)) { for (const item of value) collectActions(item,actions); return }
  if (!value || typeof value !== "object") return
  for (const [key,nested] of Object.entries(value as Record<string,unknown>)) {
    if (key === "Action") {
      if (typeof nested === "string") actions.add(nested)
      else if (Array.isArray(nested)) for (const action of nested) if (typeof action === "string") actions.add(action)
    }
    collectActions(nested,actions)
  }
}
