import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs"
import path from "node:path"
import * as cdk from "aws-cdk-lib"
import { RagEngineeringStack } from "../lib/rag-engineering-stack"

const app=new cdk.App(); const stack=new RagEngineeringStack(app,"InventoryStack")
const artifact=app.synth().getStackArtifact(stack.artifactId)
type TemplateResource={ Type:string; DeletionPolicy?:string; Properties?:unknown }
type TemplateParameter={ Type?:string; Default?:unknown; Description?:string }
type TemplateOutput={ Description?:string }
type CloudFormationTemplate={
  Resources?:Record<string,TemplateResource>
  Parameters?:Record<string,TemplateParameter>
  Outputs?:Record<string,TemplateOutput>
}
const template=artifact.template as CloudFormationTemplate
const resources=template.Resources ?? {}
const counts=new Map<string,number>()
for (const resource of Object.values(resources)) counts.set(resource.Type,(counts.get(resource.Type)??0)+1)
const actions=new Set<string>()
collectActions(resources,actions)
const outputDir=path.resolve(__dirname,"../../docs/generated")
const detailDir=path.join(outputDir,"infra-inventory")
const grouped=new Map<string,Array<[string,TemplateResource]>>()
for (const entry of Object.entries(resources).sort()) {
  const values=grouped.get(entry[1].Type) ?? []
  values.push(entry)
  grouped.set(entry[1].Type,values)
}
const body=[
  "# AWS リソースインベントリ",
  "",
  "<!-- This file is generated by npm run docs:infra. Do not edit manually. -->",
  "> 自動生成: `infra/scripts/generate-inventory.ts`",
  ">",
  "> 入力: CDK synth CloudFormation template",
  ">",
  "> CloudFormation template の静的解析です。deploy 後に AWS 側で自動作成される補助リソースや実行時データは含みません。",
  "",
  "## 全体サマリ",
  "",
  `- Stack: \`${stack.stackName}\``,
  `- Total resources: ${Object.keys(resources).length}`,
  `- Resource types: ${counts.size}`,
  "",
  "## CloudFormation Type 別リソース数",
  "",
  "| CloudFormation type | Count | Detail |",
  "| --- | ---: | --- |",
  ...[...counts].sort().map(([type,count])=>`| \`${type}\` | ${count} | [詳細](infra-inventory/${typeSlug(type)}.md) |`),
  "",
  "## リソース別主要設定",
  "",
  "| Logical ID | Type | Deletion policy | Purpose |",
  "| --- | --- | --- | --- |",
  ...Object.entries(resources).sort().map(([id,resource])=>`| \`${id}\` | \`${resource.Type}\` | \`${resource.DeletionPolicy ?? "Delete"}\` | ${purpose(id,resource.Type)} |`),
  "",
  "## Parameters",
  "",
  "| Name | Type | Default | Description |",
  "|---|---|---|---|",
  ...Object.entries(template.Parameters ?? {}).sort().map(([name,parameter])=>`| \`${name}\` | \`${parameter.Type ?? "-"}\` | ${parameter.Default === undefined ? "required" : `\`${String(parameter.Default)}\``} | ${parameter.Description ?? "-"} |`),
  "",
  "## Outputs",
  "",
  "| Name | Description |",
  "|---|---|",
  ...Object.entries(template.Outputs ?? {}).sort().map(([name,output])=>`| \`${name}\` | ${output.Description ?? "-"} |`),
  "",
  "## IAM action inventory",
  "",
  ...[...actions].sort().map(action=>`- \`${action}\``),
  "",
  "## 注意事項",
  "",
  "- 値はsynth時点の静的表現です。tokenはCloudFormation intrinsicとして要約されます。",
  "- deployはこのgeneratorおよびdocs taskの対象外です。",
  ""
].join("\n")
const inventory={generatedBy:"infra/scripts/generate-inventory.ts",source:"CDK synth CloudFormation template",stackName:stack.stackName,totalResources:Object.keys(resources).length,countsByType:[...counts].sort().map(([type,count])=>({type,count,detailFilePath:`infra-inventory/${typeSlug(type)}.md`})),resources:Object.entries(resources).sort().map(([logicalId,resource])=>({logicalId,type:resource.Type,deletionPolicy:resource.DeletionPolicy ?? "Delete",purpose:purpose(logicalId,resource.Type),properties:resource.Properties ?? {}})),parameters:template.Parameters ?? {},outputs:template.Outputs ?? {},iamActions:[...actions].sort()}
const outputs=new Map<string,string>([
  [path.join(outputDir,"infra-inventory.md"),body],
  [path.join(outputDir,"infra-resource-inventory.json"),`${JSON.stringify(inventory,null,2)}\n`],
  ...[...grouped].map(([type,entries])=>[path.join(detailDir,`${typeSlug(type)}.md`),renderTypeDetail(type,entries)] as [string,string])
])
if (process.argv.includes("--check")) {
  const stale=[...outputs].filter(([file,content])=>!existsSync(file)||readFileSync(file,"utf8")!==content).map(([file])=>path.relative(path.resolve(__dirname,"../.."),file))
  if(stale.length) throw new Error(`Infra inventory docs are stale:\n${stale.map(file=>`- ${file}`).join("\n")}`)
} else {
  mkdirSync(detailDir,{recursive:true})
  for(const [file,content] of outputs) writeFileSync(file,content)
}

function typeSlug(type:string):string { return type.toLowerCase().replaceAll("::","-").replaceAll(/[^a-z0-9-]/g,"-") }
function purpose(logicalId:string,type:string):string {
  const id=logicalId.toLowerCase()
  if(type.includes("KnowledgeBase")) return "認可済みRAG retrieval基盤"
  if(type.includes("Vector")) return "埋め込みvector索引"
  if(type.includes("Lambda")) return id.includes("provider") ? "CDK custom resource provider" : "FastAPI runtimeまたは補助処理"
  if(type.includes("S3")) return id.includes("web") ? "private Web asset配信" : "暗号化されたsourceまたはlog保管"
  if(type.includes("CloudFront")) return "WebとAPIの統合配信"
  if(type.includes("Cognito")) return "利用者認証とgroup認可"
  if(type.includes("AppSync")) return "ingestion状態のrealtime通知"
  if(type.includes("ApiGateway")) return "REST API公開境界"
  if(type.includes("IAM")) return "最小権限の実行権限"
  if(type.includes("KMS")) return "保存データ暗号化"
  if(type.includes("Alarm")||type.includes("Dashboard")||type.includes("Logs")) return "監視・監査・運用可視化"
  if(type.includes("Budget")) return "月次cost guardrail"
  return "CloudFormation managed resource"
}
function renderTypeDetail(type:string,entries:Array<[string,TemplateResource]>):string {
  const lines=[`# ${type} resource inventory`,"","<!-- This file is generated by npm run docs:infra. Do not edit manually. -->","> 自動生成: `infra/scripts/generate-inventory.ts`","", "## サマリ","",`- CloudFormation type: \`${type}\``,`- Count: ${entries.length}`,"","## リソース一覧",""]
  for(const [logicalId,resource] of entries) lines.push(`### \`${logicalId}\``,"",`- Purpose: ${purpose(logicalId,type)}`,`- Deletion policy: \`${resource.DeletionPolicy ?? "Delete"}\``,"","#### Properties","","```json",JSON.stringify(resource.Properties ?? {},null,2),"```","")
  return lines.join("\n")
}

function collectActions(value:unknown,actions:Set<string>):void {
  if (Array.isArray(value)) { for (const item of value) collectActions(item,actions); return }
  if (!value || typeof value !== "object") return
  for (const [key,nested] of Object.entries(value as Record<string,unknown>)) {
    if (key === "Action") {
      if (typeof nested === "string") actions.add(nested)
      else if (Array.isArray(nested)) for (const action of nested) if (typeof action === "string") actions.add(action)
    }
    collectActions(nested,actions)
  }
}
