import argparse
import json
from pathlib import Path
from typing import cast

from app.design_contract import MESSAGE_CATALOG, OPERATIONS
from app.main import app

ROOT = Path(__file__).resolve().parents[2]
OPENAPI = ROOT / "docs/generated/openapi.json"
API_LIST = ROOT / "docs/generated/api-list.md"
API_DETAILS = ROOT / "docs/generated/api-details.md"
API_SEQUENCES = ROOT / "docs/generated/api-sequences.md"
MESSAGE_CATALOG_PATH = ROOT / "docs/generated/message-catalog.md"
TEST_FACTORS = ROOT / "docs/generated/api-test-factors.md"


def render() -> dict[Path, str]:
    schema = app.openapi()
    _validate_contracts(schema)
    rows = ["# API 一覧", "", "| Method | Path | Summary |", "|---|---|---|"]
    for path, operations in sorted(schema["paths"].items()):
        for method, operation in sorted(operations.items()):
            rows.append(f"| {method.upper()} | `{path}` | {operation.get('summary', '')} |")
    return {
        OPENAPI: json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        API_LIST: "\n".join(rows) + "\n",
        API_DETAILS: _render_details(),
        API_SEQUENCES: _render_sequences(),
        MESSAGE_CATALOG_PATH: _render_messages(),
        TEST_FACTORS: _render_test_factors(),
    }


def _validate_contracts(schema: dict[str, object]) -> None:
    paths = schema.get("paths")
    if not isinstance(paths, dict):
        raise ValueError("OpenAPI paths are missing")
    runtime_ids: set[str] = set()
    path_map = cast("dict[str, object]", paths)
    for path_item_value in path_map.values():
        if not isinstance(path_item_value, dict):
            continue
        path_item = cast("dict[str, object]", path_item_value)
        for operation_value in path_item.values():
            if not isinstance(operation_value, dict):
                continue
            operation = cast("dict[str, object]", operation_value)
            operation_id = operation.get("operationId")
            if isinstance(operation_id, str):
                runtime_ids.add(operation_id)
    contract_ids = {operation.operation_id for operation in OPERATIONS}
    if runtime_ids != contract_ids:
        raise ValueError(
            "operation contract drift: "
            f"runtime={sorted(runtime_ids)}, contract={sorted(contract_ids)}"
        )


def _render_details() -> str:
    lines = ["<!-- Generated by uv run app-docs. Do not edit. -->", "", "# API detail design", ""]
    for operation in OPERATIONS:
        lines.extend(
            [
                f"## `{operation.operation_id}`",
                "",
                f"- Interface: `{operation.method.upper()} {operation.path}`",
                f"- Auth: `{operation.auth_mode}`",
                f"- Permission: `{operation.permission}`",
                f"- Business summary: {operation.business_summary}",
                "",
            ]
        )
    return "\n".join(lines)


def _render_sequences() -> str:
    lines = ["<!-- Generated by uv run app-docs. Do not edit. -->", "", "# API sequences", ""]
    for operation in OPERATIONS:
        lines.extend([f"## `{operation.operation_id}`", "", "```mermaid", "sequenceDiagram"])
        for index, step in enumerate(operation.sequence, start=1):
            lines.append(f"    API->>Pipeline: {index}. {step}")
        lines.extend(["```", ""])
    return "\n".join(lines)


def _render_messages() -> str:
    lines = [
        "<!-- Generated by uv run app-docs. Do not edit. -->",
        "",
        "# Message catalog",
        "",
        "| Code | Meaning |",
        "|---|---|",
    ]
    lines.extend(f"| `{code}` | {meaning} |" for code, meaning in sorted(MESSAGE_CATALOG.items()))
    return "\n".join(lines) + "\n"


def _render_test_factors() -> str:
    lines = [
        "<!-- Generated by uv run app-docs. Do not edit. -->",
        "",
        "# API test factors",
        "",
        "| Operation | Factor |",
        "|---|---|",
    ]
    for operation in OPERATIONS:
        lines.extend(
            f"| `{operation.operation_id}` | {factor} |" for factor in operation.test_factors
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate implementation-derived API design")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render()
    if args.check:
        stale = [
            str(path.relative_to(ROOT))
            for path, body in generated.items()
            if not path.exists() or path.read_text() != body
        ]
        if stale:
            raise SystemExit("stale generated docs: " + ", ".join(stale))
        return
    for path, body in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
