from app.apis.contract import ApiContract, MessageContract

CONTRACT = ApiContract(
    operation_id="searchEvidence",
    markdown_slug="retrieval/search_evidence",
    method="POST",
    path="/v1/search",
    summary="認可済み根拠を検索する",
    description="ACL hard filter後に疎密ハイブリッド検索と順位融合を行います。",
    auth_mode="management-bearer",
    business_summary="認証主体が参照できる根拠だけを疎密検索し、RRF順位で返す。",
    permissions=("authenticated",),
    sequence=("normalize_query", "retrieve_authorized_evidence", "build_search_response"),
    prerequisites=("Bearer access tokenが検証済みである。", "ACL filterを検索前に適用する。"),
    resource_changes=(),
    response_sources=(
        ("hits", "ChunkStore hybrid retrieval result"),
        ("requestId", "Application generated UUID"),
    ),
    test_factors=(
        "認証",
        "query正規化",
        "ACL hard filter",
        "疎検索",
        "密検索",
        "RRF",
        "重複排除",
        "topK境界",
    ),
    messages=(
        MessageContract(
            "M001",
            "searchEvidence.completed",
            "INFO",
            "認可済み根拠の検索を完了した。",
            "検索結果を返却した場合。",
            "resultCountと検索遅延を確認する。",
            "RUNBOOK-retrieval-quality",
            ("traceId", "actorPrincipalId", "resultCount", "durationMs"),
        ),
        MessageContract(
            "M002",
            "searchEvidence.failed",
            "ERROR",
            "根拠検索に失敗した。",
            "検索providerまたは入力処理で例外が発生した場合。",
            "provider状態とtraceIdを確認する。",
            "RUNBOOK-retrieval-failure",
            ("traceId", "actorPrincipalId", "errorCode", "exceptionType"),
        ),
    ),
    sql_summary="ACL適用済みhybrid retrieval境界を仕様化する。",
    sql_tables=("s3_vectors", "bedrock_knowledge_base"),
)
